# Curating the look, feel, and features {#curate-features}

This chapter teaches you how to edit the look and feel of your website and how to personalize certain features including logos, page navigation, contact forms, and social media links.

## How it works

Recall that the types of static websites described in this book are simply a collection of text files including Markdown, HTML, CSS, and Javascript file types that Hugo compiles into a website. Therefore, changes to the look, feel, and features of your website are done simply by editing the relevant files and folders that make up your website.

#### Editing the look and feel with CSS {-}

If you are not familiar with CSS (Cascading Style Sheets), take a look at [this CSS stylesheet](https://github.com/dannymorris/r4sites-demo-anatole/blob/master/themes/anatole/assets/css/style.css). While HTML defines the general layout of a webpage, CSS is used to control the appearance of an HTML webpage and its elements including font styles, colors, buttons and links, positioning and dimensions of images, and so on. If you intend to alter the look and feel of your website, you will likely be spending most of your time editing your website's primary CSS files.

To learn more about CSS, visit [w3schools](https://www.w3schools.com/css/) for tutorials and read about using the [Inspect tool](#inspect-tool) in your browser.

#### Editing features related to content and navigation {-}

Personal websites and blogs typically have the following navigation pages and content features: Home, Blog, Projects, About Me, and Contact. The [Anatole demo website](https://r4sites-anatole.netlify.app/) has a similar structure with some minor differences.

The presence or absence of content and navigation pages is dependent upon the existance of folders and files located in the `content` folder in the main website directory. For example, the [Anatole demo website](https://r4sites-anatole.netlify.app/) contains navigation links to pages titled Home, Posts, About, and Contact. These features have supporting files in the `content` folder in the main website directory, as shown in the [website's content folder](https://github.com/dannymorris/r4sites-demo/tree/master/content/english).

To **remove content and features**, you can do one of the following: delete the relevant folder in the `content` directory (e.g. delete the `posts` folder), or (recommended) edit the `config.yaml` file to explicity define the content and features you want on your site, as shown in [this example]().

## Tips for working efficiently

#### Using the browser's Inspect tool {-#inspect-tool}

The "Inspect" tool in your browser is an essential tool for experimenting with changes to CSS and HTML directly in the browser. Using the Inspect tool results in temporary changes, and when the browser is refreshed the original properties are restored. Access this tool in the browser by right-clicking on any page element you want to edit (e.g. images, text, links, buttons) and click on "Inspect", as shown in this [example](https://i.imgur.com/0h0H4VW.png)

Practice using the Inspect tool with these examples:

1. Visit [Google](https://www.google.com/) and edit the "Google Search" button by changing the background color and font color. [Watch the video demonstration on YouTube](https://youtu.be/6tR1u7UxmgU). After changing the background color and font color of the search button, feel free to experiment with changing other properties as well.

2. Vist [this question on Stack Overflow](https://stackoverflow.com/questions/45851032/r-for-data-science-book-wickham-cannot-reproduce-example) and practice editing image dimensions, colors of links and bold text, and code snippets. [Watch the video demonstration on YouTube](https://youtu.be/pJd0dWU70gk)

#### Serve the site locally {-}

Once you have generated a website using the Anatole theme, run `blogdown::serve_site()` in the R console from within your RStudio Project to render a live, local copy of the website. To learn about serving the site locally, read [this section](#serve-site).

## Use case

To keep things simple, we will focus on a use case that revolves around tweaking the [Anatole](https://themes.gohugo.io/anatole/) theme. To begin, follow the instructions outlined in [Generating websites from themes](#create-site-with-theme). Then, follow along with the steps below. The theme's demo website can be found here - https://themes.gohugo.io/theme/anatole/. The finished product resulting from the following steps can be found here - https://r4sites-anatole.netlify.app/.

## Title and description

The title of the Anatole demo website is "My Blog". To change this to something more personal, navigate to `config/_default/languages.toml` and edit the `title` parameter.  [Example](https://github.com/dannymorris/r4sites-demo-anatole/blob/master/config/_default/languages.toml#L2).

## Logos and profile images

The profile image is the main image on the homepage with a circular border. To edit this, navigate to `static/images/` and replace `profile.jpg` with your own image ([example](https://github.com/dannymorris/r4sites-demo-anatole/tree/master/static/images)). Keep the file named `profile.jpg` so the theme will recognize your image. 

If your image appears too wide/narrow or too tall/short, navigate to `themes/anatole/assets/css/style.css` and edit the CSS properties. For this theme, you will need to edit the CSS properties [here](https://github.com/dannymorris/anatole-site/blob/a114905a32be5619a5ecd3ab48d81d8220b14ed3/themes/anatole/assets/css/style.css#L901-L904) for narrow screen devices and [here](https://github.com/dannymorris/anatole-site/blob/master/themes/anatole/assets/css/style.css#L291-L295) for wide
screen devices.

## Favicons {#favicon}

Navigate to `static/favicons/` and replace `favicon.ico` with your own favicon. The favicon is the tiny image that appears in the web browser tab for your website. To create a favicon from an image, visit https://favicon.io/favicon-converter/. Keep the file named `favicon.ico` in the same folder.

## Fonts

If you don't like the default font, you can easily change it. For example, to use the Google Font [Quicksand](https://fonts.google.com/specimen/Quicksand) insert [this line of code](https://github.com/dannymorris/anatole-site/blob/master/themes/anatole/layouts/partials/head.html#L114-L116) in the `themes/anatole/layouts/partials/head.html` file. Then, navigate to `themes/anatole/assets/css/style.css` and change the font property in the `body` element [(example)](https://github.com/dannymorris/anatole-site/blob/master/themes/anatole/assets/css/style.css#L44-L51). You can also change basic font properties (e.g. size, color), but you will have to know what CSS class to change. Examples include `p`([example](https://github.com/dannymorris/anatole-site/blob/a114905a32be5619a5ecd3ab48d81d8220b14ed3/themes/anatole/assets/css/style.css#L53-L57)), `.page-top .nav`([example](https://github.com/dannymorris/anatole-site/blob/master/themes/anatole/assets/css/style.css#L198-L205)), and `.page-top .nav a`([example](https://github.com/dannymorris/anatole-site/blob/a114905a32be5619a5ecd3ab48d81d8220b14ed3/themes/anatole/assets/css/style.css#L213-L215)).

## Colors

## Managing pages and sections

## Contact forms

## Foreign languages

7. **(optional) Remove all content supporting a language translation**. By default, the Anatole theme supports an Arabic language translation. To remove all content supporting this translation, delete the file `config/_default/menus.ar.toml`, edit the file `config/_default/languages.toml` by removing all Arabic language parameters ([example](https://github.com/dannymorris/anatole-site/blob/master/config/_default/languages.toml)), then delete the folder `content/arabic/` and all of its contents.

## Social media links

Navigate to config/_default/params.toml and edit the links to your social medial accounts beginning on line 40. Example

## Closing thoughts on themes

Relying on themes is the quickest way to launch a professional website. Editing the look and feel of your website can be a lot of fun, but you must be careful not to go overboard. Here are some tips to keep in the back of your mind while you're editing your theme:

- Before you make any edits, go ahead and run `blogdown::serve_site()` in the R console within the RStudio Project. This will launch your website locally and will update automatically whenever edits are detected.

- Whenever you make a change, check the result on wide and narrow screens. You can do this with the browser on your desktop by maximizing the browser width (wide screen) and decreasing the width to mimic a mobile device (narrow screen).

- Try not to edit the theme's default *layout.* Instead, focus on colors, font, images, and content to reflect you personal style.

- After you make a change, carefully scrutinize the result and look for any unexpected consequences.