# Going live on the internet {#deploy}

This chapter describes a simple, repeatable approach to putting your website on the internet. 

## Prerequisites

Before you proceed, complete the following prerequisites:

1. [Choose your preferred style](#choose-theme)
2. [Generate your website](#generate)
3. (optional) [Fine tune the look and feel](#fine-tune)
4. (optional) [Configure pages and features](#pages-features)
5. Install [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
6. Sign up for [GitHub](https://github.com/)
7. Sign up for [Netlify](https://app.netlify.com/)

## How it works

Hugo (the static site generator used by blogdown), GitHub, and Netlify are the three tools that make it incredibly simple to deploy your website to the internet. The main steps are to upload your website files to a remote GitHub repository, then create a new site in Netlify that points to your GitHub repository URL. Netlify will then do all of the heavy lifting of building and deploying your Hugo website to the internet. All of this can be done in a matter of minutes with just a few lines of code and a few clicks.

## Upload files to GitHub {#initial-push}

Once your website is working locally, the next steps are to create a remote GitHub repository for your website files, configure a local Git repository, and push your website files from your local Git repository to your remote GitHub repository. Follow these simple steps to make this happen:

1. Sign in to [GitHub](https://github.com/) and create a new repository by clicking "New" in the Repositories section. Configure the repository accordingly, then click "Create repository". [📷 Image](https://i.imgur.com/dnmI973.png)

2. On your local machine, launch Git from the command line (e.g. Git Bash on Windows, Terminal on Mac/Linux) and run the following Git commands to sync a local Git repository with your newly created remote GitHub repository.  

```{bash, eval=F}
# Change the directory to your website's root folder
cd path/to/your/website

# initialize local Git repository
git init

# add all of your website files to the local Git repository
git add --all

# commit your website files to the local Git repository
git commit -m "first commit"

# sync the local Git repository with the remote GitHub repository
# change your_username and your_repo to your GitHub username and repository name
git remote add origin https://github.com/your_username/your_repo.git

# push your files to GitHub
git push -u origin master
```

## Configure Netlify for deployment

Now that your website files are stored in GitHub, use Netlify to deploy your website. Netlify will deploy your website directly from your GitHub repository. Any time you push new or edited content to the GitHub repository, Netlify will automatically deploy a new version of your website. This is known as continuous deployment and is key to rapid iteration. 

Follow these steps to deploy your website on Netlify:

1. Log in to [Netlify](https://app.netlify.com/) and click "New site from Git".

2. Select GitHub as the Continuous Deployment provider, then choose your website's GitHub repository.

3. Leave the site settings alone and click "Deploy site" to publish your website. [📷 Image](https://i.imgur.com/wjDFnvJ.png)

4. After a few seconds, your website will be deployed on Netlify. To view your website on the internet, return to the Site Overview section and locate the default domain name generated by Netlify ([📷 Image](https://i.imgur.com/t6IW44i.png)). 

5. Change your website's domain name (part of it at least). Default Netlify domain names tend to look something like this - https://dazzling-khorana-a6a8fe.netlify.app. To change this, go to *Site settings > Change site name*. Note that the domain extension is `.netlify.app` until you (optionally) purchase a custom domain name.

## Updating your website

To update the published version of your website, simply push your changes from your local environment to your GitHub repository. Netlify will detect the update to your GitHub repository and immediately proceed with publishing the latest version of your website.

Assuming you have [pushed your website to GitHub](#inital-push) already, use the **add** > **commit** > **push** Git workflow to push your updates to GitHub. [📷 Image](https://i.imgur.com/zJNAlIB.png)

```
# add all files to the local Git repository
git add --all

# commit files and include a brief message
git commit -m "brief message describing your changes"

# push files to GitHub
git push origin master
```

## Purchasing a custom domain name

Netlify's default domain names end with `.netlify.app`. If you don't care for this domain extension, you can purchase a custom domain for your website. Though several domain registrars exist, the simplest route is to purchase a domain name through Netlify. If you use a domain registrar other than Netlify (e.g. Google Domains), you will have to manually configure Domain Name Servers and Domain Name System settings. With Netlify, all of this is taken care of for you.

Follow the simple steps below to purchase a custom domain through Netlify:

1. Log in to [Netlify](https://app.netlify.com/), open your site, and click on "Domain settings". [📷 Image](https://i.imgur.com/ACjNs4w.png).

2. Under Custom domains, click "Add custom domain".

3. Search for a domain name you like, then click "Verify" to determine if the domain is already owned or available for purchase. If available, confirm the purchase with a credit card and (optionally) set the domain name to auto-renew annually. [📷 Image](https://i.imgur.com/y2s7wQR.png).

4. Enable IPv6 to reach areas of the world where connectivity via IPv4 is not possible. Do this by signing in to Netlify and navigating to *Team overview > Domains*, select your custom domain name, and click "Enable IPv6 on your domain". [📷 Image](https://docs.netlify.com/domains-https/netlify-dns/#ipv6-traffic).

