---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include = F}
knitr::opts_chunk$set(echo = T, message = F, warning = F, eval=T)
```

# Getting help {#get-help}

Despite the wealth of information in this book, it does not (and simply cannot) cover all possible topics and ideas relevant to the subject of the book. Firstly, this book recommends several Hugo themes yet a single theme is used as the basis for explaining and implementing concepts. Secondly, the number of edits that can be applied to any given website design is infinite yet this book implements a small, finite number of edits. I suspect many readers will want to venture beyond the scope of this book and pursue topics that are not discussed in this book.

## Join the Slack workspace

The Slack workspace is the best way to get help with your own website project. Slack is a place to chat, share files, and interact with others including myself.

[Accept this invitation](https://join.slack.com/t/r4sitesbooksupport/shared_invite/zt-pyua4ua9-L~taaOqLzEeCbW5o9w9eLQ) to join the Slack workspace.

## Connect with me

Readers are welcome to reach out to me directly via [email](mailto:dmorris10667@gmail.com) or [LinkedIn](https://www.linkedin.com/in/drmorris87/).

## Additional resources

To learn more about the methodology and the tools described in this book, I recommend the following resources:

- [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/)

- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

- [googleAnalyticsR](https://code.markedmondson.me/googleAnalyticsR/)

- [Hugo documentation](https://gohugo.io/documentation/)

- [Netlify documentation](https://docs.netlify.com/)

- [Formspree documentation](https://formspree.io/formbutton/docs)