# Tips and tricks {#tips-tricks}

This chapter reinforces some basic tips and tricks for you to consider while developing your website.

## Serve your website locally {#serve-local}

The blogdown package includes a handy function called `serve_site()`. Running this function in the R console with your website's RStudio Project loaded will render a local copy of your entire website in the RStudio "Viewer" pane, as shown in this [example](https://i.imgur.com/oxZgeqM.png).

While serving your website locally, the local version will update in real-time as you make and save changes to your website's codebase. This feature of blogdown, known as LiveReload, lets you experiment with changes to your website and receive instant feedback.

## Push updates to GitHub

Any time you make changes to your website, such as integrating Google Analytics or authoring a new post, you will need to push these changes to your GitHub repository to force Netlify to rebuild and redeploy your website to the internet.

Assuming you have already [pushed your website to GitHub](#inital-push), use the **add** > **commit** > **push** Git workflow to push updates. I recommend pushing updates frequently to keep your GitHub repository up-to-date.

```{bash, eval=F}
# add all files to the local Git repository
git add --all

# commit files and include a brief message
git commit -m "brief message describing your changes"

# push files to GitHub
git push origin master
```

## Check your website

At any point during the development of your website, consider running `blogdown::check_site()` in the R console. This function will run a number of checks against your website to discover any problems.

## Rebuild a clean website

While developing your website, you should be [serving your website locally](#serve-local) to observe the effects of your edits in real-time. Sometimes, for a number of reasons, the local rendering of your website ceases to reflect your edits. If this or any other issue surfaces, I recommend running the following R code to rebuild a clean website:

```{r, eval=F}
# clean the website generated by blogdown
rmarkdown::clean_site()

# build the website
blogdown::build_site()

# serve the website locally
blogdown::serve_site()
```

If you continue to experience buggy behavior, try restarting RStudio and running the code again.

## Finding free images

If you need images for your website (e.g. post thumbnail), I recommend using free images from [Unsplash](https://unsplash.com/). 
